"""Add paper broker

Revision ID: 7d2982ad2238
Revises: 
Create Date: 2026-09-29 19:40:53.138967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2982ad2238'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('available_cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_paper_accounts_id'), 'paper_accounts', ['id'], unique=False)
    op.create_table('paper_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.Enum('STOCK', 'ETF', 'MUTUAL_FUND', 'INDEX_FUND', 'OTHER', name='assettype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_holdings_id'), 'paper_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_paper_holdings_symbol'), 'paper_holdings', ['symbol'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.Enum('STOCK', 'ETF', 'MUTUAL_FUND', 'INDEX_FUND', 'OTHER', name='assettype'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'REJECTED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_client_order_id'), 'paper_orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_paper_orders_id'), 'paper_orders', ['id'], unique=False)
    op.create_index(op.f('ix_paper_orders_symbol'), 'paper_orders', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_orders_symbol'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_client_order_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_paper_holdings_symbol'), table_name='paper_holdings')
    op.drop_index(op.f('ix_paper_holdings_id'), table_name='paper_holdings')
    op.drop_table('paper_holdings')
    op.drop_index(op.f('ix_paper_accounts_id'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
